import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
   return (
      <div className="">
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <nav className="fixed top-0 w-full h-20 bg-gray-500"></nav>
         <main className="bg-blue-500">Hello</main>
      </div>
   );
};

export default Home;
