import type { NextPage } from "next";
import { Swiper, SwiperSlide } from "swiper/react";
import Head from "next/head";
import Slides from "../components/Slides";

import { Pagination } from "swiper";
import "swiper/css";
import "swiper/css/pagination";

const array = [
   "cheese",
   "frozen",
   "beef",
   "dick",
   "cock",
   "meat",
   "milk",
   "dairy",
   "sea food",
   "juices",
   "liquor",
   "bakery",
   "vegetables",
   "deli",
   "cereals",
   "fruits",
   "drinks",
   "cleaning",
   "chocolate",
   "pussy",
];

const Home: NextPage = () => {
   return (
      <div className="">
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <nav className="fixed top-0 w-full h-40 bg-gray-200">
            <div className="flex justify-between items-center px-20">
               <div>Chek-Inventory</div>
               <div className="h-20 flex items-center justify-center">
                  <input
                     type="text"
                     className="rounded-full bg-white h-10 shadow-md w-72 outline-none px-5"
                  />
               </div>
               <div>Options</div>
            </div>
            <div className="h-20 flex space-x-10 items-center px-20 custom-pagination overflow-x-auto"></div>
         </nav>
         <main className="bg-blue-500 h-screen w-full pt-40">
            <Swiper
               speed={1500}
               className="bg-gray-200 h-full w-full"
               spaceBetween={10}
               slidesPerView={1}
               onSlideChange={() => console.log("slide change")}
               pagination={{
                  el: ".custom-pagination",
                  bulletClass: "custom-bullet",
                  bulletActiveClass: "custom-bullet-active",
                  clickable: true,
                  renderBullet: function (index, className) {
                     return (
                        '<span class="' +
                        className +
                        '">' +
                        array[index] +
                        "</span>"
                     );
                  },
               }}
               modules={[Pagination]}
               onSwiper={(swiper: any) => console.log(swiper)}
            >
               {array.map((hall, index) => (
                  <SwiperSlide key={index}>
                     <Slides />
                  </SwiperSlide>
               ))}
            </Swiper>
         </main>
      </div>
   );
};

export default Home;
